begin;

create table if not exists public.plan_mutation_receipts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  request_id text not null,
  operation text not null,
  plan_id uuid not null,
  response jsonb not null,
  created_at timestamptz not null default now(),
  constraint plan_mutation_receipts_client_length check (char_length(client_id) between 1 and 200),
  constraint plan_mutation_receipts_request_length check (char_length(request_id) between 8 and 120),
  constraint plan_mutation_receipts_operation_valid check (operation in ('create', 'revise', 'archive')),
  constraint plan_mutation_receipts_response_object check (jsonb_typeof(response) = 'object'),
  unique (user_id, client_id, request_id)
);

create index if not exists plan_mutation_receipts_user_client_created_idx
  on public.plan_mutation_receipts (user_id, client_id, created_at desc);

alter table public.plan_mutation_receipts enable row level security;

revoke all on table public.plan_mutation_receipts from public, anon, authenticated;
grant select, insert on table public.plan_mutation_receipts to authenticated;
grant insert on table public.study_plan_revisions to authenticated;

create or replace function public.wenyan_has_oauth_capability(p_capability text)
returns boolean
language sql
stable
security invoker
set search_path = ''
as $$
  select
    auth.uid() is not null
    and nullif(auth.jwt() ->> 'client_id', '') is not null
    and exists (
      select 1
      from public.oauth_client_capabilities as c
      where c.user_id = auth.uid()
        and c.client_id = auth.jwt() ->> 'client_id'
        and c.capability = p_capability
    );
$$;

create or replace function public.wenyan_validate_plan_tasks(p_tasks jsonb)
returns void
language plpgsql
immutable
security invoker
set search_path = ''
as $$
begin
  if p_tasks is null
     or jsonb_typeof(p_tasks) <> 'array'
     or jsonb_array_length(p_tasks) < 1
     or jsonb_array_length(p_tasks) > 60 then
    raise exception 'invalid_tasks' using errcode = '22023';
  end if;

  if exists (
    select 1
    from jsonb_array_elements(p_tasks) as items(item)
    where jsonb_typeof(item) <> 'object'
      or coalesce(item ->> 'kind', '') not in (
        'chapter', 'smart_review', 'word_set', 'dictation', 'weak_words', 'mixed_session'
      )
      or char_length(coalesce(item ->> 'title', '')) not between 1 and 160
      or char_length(coalesce(item ->> 'reason', '')) > 1000
      or coalesce(item ->> 'dueDate', '') !~ '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
      or case
        when coalesce(item ->> 'estimatedMinutes', '') ~ '^[0-9]+$'
          then (item ->> 'estimatedMinutes')::integer not between 1 and 240
        else true
      end
      or (item ? 'config' and jsonb_typeof(item -> 'config') <> 'object')
  ) then
    raise exception 'invalid_task_shape' using errcode = '22023';
  end if;
end;
$$;

create or replace function public.wenyan_plan_snapshot(p_plan_id uuid)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select jsonb_build_object(
    'schemaVersion', 2,
    'plan', jsonb_build_object(
      'id', p.id,
      'title', p.title,
      'timezone', p.timezone,
      'status', p.status,
      'revision', p.revision,
      'source', p.source,
      'createdByClientId', p.created_by_client_id,
      'createdAt', p.created_at,
      'updatedAt', p.updated_at
    ),
    'tasks', coalesce((
      select jsonb_agg(
        jsonb_build_object(
          'id', t.id,
          'position', t.position,
          'kind', t.kind,
          'title', t.title,
          'dueDate', t.due_date,
          'estimatedMinutes', t.estimated_minutes,
          'reason', t.reason,
          'config', t.config,
          'state', t.state
        ) order by t.position
      )
      from public.plan_tasks as t
      where t.plan_id = p.id and t.user_id = p.user_id
    ), '[]'::jsonb)
  )
  from public.study_plans as p
  where p.id = p_plan_id and p.user_id = auth.uid();
$$;

revoke all on function public.wenyan_has_oauth_capability(text) from public, anon, authenticated;
revoke all on function public.wenyan_validate_plan_tasks(jsonb) from public, anon, authenticated;
revoke all on function public.wenyan_plan_snapshot(uuid) from public, anon, authenticated;
grant execute on function public.wenyan_has_oauth_capability(text) to authenticated;
grant execute on function public.wenyan_validate_plan_tasks(jsonb) to authenticated;
grant execute on function public.wenyan_plan_snapshot(uuid) to authenticated;

drop policy if exists "plan_mutation_receipts_select_own_client" on public.plan_mutation_receipts;
create policy "plan_mutation_receipts_select_own_client"
  on public.plan_mutation_receipts
  for select
  to authenticated
  using (
    auth.uid() = user_id
    and (
      (auth.jwt() ->> 'client_id') is null
      or (auth.jwt() ->> 'client_id') = client_id
    )
  );

-- OAuth plan writes are allowed only while one of Wenyan's narrow plan RPCs
-- has set the transaction-local marker. Possessing the OAuth token and the
-- capability alone is therefore not enough for direct table mutation.
drop policy if exists "study_plans_insert_oauth_rpc" on public.study_plans;
create policy "study_plans_insert_oauth_rpc"
  on public.study_plans
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and current_setting('wenyan.plan_write_rpc', true) = '1'
    and public.wenyan_has_oauth_capability('plans:write')
  );

drop policy if exists "study_plans_update_oauth_rpc" on public.study_plans;
create policy "study_plans_update_oauth_rpc"
  on public.study_plans
  for update
  to authenticated
  using (
    auth.uid() = user_id
    and current_setting('wenyan.plan_write_rpc', true) = '1'
    and public.wenyan_has_oauth_capability('plans:write')
  )
  with check (
    auth.uid() = user_id
    and current_setting('wenyan.plan_write_rpc', true) = '1'
    and public.wenyan_has_oauth_capability('plans:write')
  );

drop policy if exists "plan_tasks_insert_oauth_rpc" on public.plan_tasks;
create policy "plan_tasks_insert_oauth_rpc"
  on public.plan_tasks
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and current_setting('wenyan.plan_write_rpc', true) = '1'
    and public.wenyan_has_oauth_capability('plans:write')
  );

drop policy if exists "plan_tasks_update_oauth_rpc" on public.plan_tasks;
create policy "plan_tasks_update_oauth_rpc"
  on public.plan_tasks
  for update
  to authenticated
  using (
    auth.uid() = user_id
    and current_setting('wenyan.plan_write_rpc', true) = '1'
    and public.wenyan_has_oauth_capability('plans:write')
  )
  with check (
    auth.uid() = user_id
    and current_setting('wenyan.plan_write_rpc', true) = '1'
    and public.wenyan_has_oauth_capability('plans:write')
  );

drop policy if exists "plan_tasks_delete_oauth_rpc" on public.plan_tasks;
create policy "plan_tasks_delete_oauth_rpc"
  on public.plan_tasks
  for delete
  to authenticated
  using (
    auth.uid() = user_id
    and current_setting('wenyan.plan_write_rpc', true) = '1'
    and public.wenyan_has_oauth_capability('plans:write')
  );

drop policy if exists "study_plan_revisions_insert_oauth_rpc" on public.study_plan_revisions;
create policy "study_plan_revisions_insert_oauth_rpc"
  on public.study_plan_revisions
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and current_setting('wenyan.plan_write_rpc', true) = '1'
    and public.wenyan_has_oauth_capability('plans:write')
  );

drop policy if exists "plan_mutation_receipts_insert_oauth_rpc" on public.plan_mutation_receipts;
create policy "plan_mutation_receipts_insert_oauth_rpc"
  on public.plan_mutation_receipts
  for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and client_id = auth.jwt() ->> 'client_id'
    and current_setting('wenyan.plan_write_rpc', true) = '1'
    and public.wenyan_has_oauth_capability('plans:write')
  );

commit;
