begin;

create table public.learning_preferences (
  user_id uuid primary key references auth.users(id) on delete cascade,
  stage text not null default 'vocabulary',
  revision integer not null default 1,
  stage_provenance jsonb not null default '{"kind":"product_default","ref":"exam-prep-strategy-v1","since":null}'::jsonb,
  stage_reminder jsonb,
  confirmed_at timestamptz,
  updated_by_client_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint learning_preferences_stage_valid check (stage in ('vocabulary', 'mixed', 'exam_practice')),
  constraint learning_preferences_revision_positive check (revision > 0),
  constraint learning_preferences_provenance_object check (jsonb_typeof(stage_provenance) = 'object'),
  constraint learning_preferences_reminder_object check (stage_reminder is null or jsonb_typeof(stage_reminder) = 'object'),
  constraint learning_preferences_client_length check (
    updated_by_client_id is null or char_length(updated_by_client_id) between 1 and 200
  )
);

create table public.learning_preference_revisions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  revision integer not null,
  snapshot jsonb not null,
  change_reason text not null default '',
  created_by_client_id text,
  created_at timestamptz not null default now(),
  constraint learning_preference_revisions_revision_positive check (revision > 0),
  constraint learning_preference_revisions_snapshot_object check (jsonb_typeof(snapshot) = 'object'),
  constraint learning_preference_revisions_reason_length check (char_length(change_reason) <= 1000),
  constraint learning_preference_revisions_client_length check (
    created_by_client_id is null or char_length(created_by_client_id) between 1 and 200
  ),
  unique (user_id, revision)
);

create index learning_preference_revisions_user_revision_idx
  on public.learning_preference_revisions (user_id, revision desc);

create table public.learning_preference_mutation_receipts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  request_id text not null,
  operation text not null,
  request_body jsonb not null,
  response jsonb not null,
  created_at timestamptz not null default now(),
  constraint learning_preference_receipts_client_length check (char_length(client_id) between 1 and 200),
  constraint learning_preference_receipts_request_length check (char_length(request_id) between 8 and 120),
  constraint learning_preference_receipts_operation_valid check (
    operation in ('confirm_stage', 'set_stage_reminder', 'clear_stage_reminder')
  ),
  constraint learning_preference_receipts_request_object check (jsonb_typeof(request_body) = 'object'),
  constraint learning_preference_receipts_response_object check (jsonb_typeof(response) = 'object'),
  unique (user_id, client_id, request_id)
);

create index learning_preference_receipts_user_client_created_idx
  on public.learning_preference_mutation_receipts (user_id, client_id, created_at desc);

alter table public.learning_preferences enable row level security;
alter table public.learning_preference_revisions enable row level security;
alter table public.learning_preference_mutation_receipts enable row level security;

revoke all on table public.learning_preferences from public, anon, authenticated;
revoke all on table public.learning_preference_revisions from public, anon, authenticated;
revoke all on table public.learning_preference_mutation_receipts from public, anon, authenticated;

grant select, insert, update on table public.learning_preferences to authenticated;
grant select, insert on table public.learning_preference_revisions to authenticated;
grant select, insert on table public.learning_preference_mutation_receipts to authenticated;

drop policy if exists "learning_preferences_select_own" on public.learning_preferences;
create policy "learning_preferences_select_own"
  on public.learning_preferences
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "learning_preferences_insert_via_rpc" on public.learning_preferences;
create policy "learning_preferences_insert_via_rpc"
  on public.learning_preferences
  for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and (select current_setting('wenyan.preference_write_rpc', true)) = '1'
    and (
      (
        nullif((select auth.jwt()) ->> 'client_id', '') is null
        and updated_by_client_id is null
      )
      or (
        nullif((select auth.jwt()) ->> 'client_id', '') is not null
        and updated_by_client_id = ((select auth.jwt()) ->> 'client_id')
        and (select public.wenyan_has_oauth_capability('preferences:write'))
      )
    )
  );

drop policy if exists "learning_preferences_update_via_rpc" on public.learning_preferences;
create policy "learning_preferences_update_via_rpc"
  on public.learning_preferences
  for update
  to authenticated
  using (
    (select auth.uid()) = user_id
    and (select current_setting('wenyan.preference_write_rpc', true)) = '1'
    and (
      nullif((select auth.jwt()) ->> 'client_id', '') is null
      or (select public.wenyan_has_oauth_capability('preferences:write'))
    )
  )
  with check (
    (select auth.uid()) = user_id
    and (select current_setting('wenyan.preference_write_rpc', true)) = '1'
    and (
      (
        nullif((select auth.jwt()) ->> 'client_id', '') is null
        and updated_by_client_id is null
      )
      or (
        nullif((select auth.jwt()) ->> 'client_id', '') is not null
        and updated_by_client_id = ((select auth.jwt()) ->> 'client_id')
        and (select public.wenyan_has_oauth_capability('preferences:write'))
      )
    )
  );

drop policy if exists "learning_preference_revisions_select_own" on public.learning_preference_revisions;
create policy "learning_preference_revisions_select_own"
  on public.learning_preference_revisions
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "learning_preference_revisions_insert_via_rpc" on public.learning_preference_revisions;
create policy "learning_preference_revisions_insert_via_rpc"
  on public.learning_preference_revisions
  for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and (select current_setting('wenyan.preference_write_rpc', true)) = '1'
    and (
      (
        nullif((select auth.jwt()) ->> 'client_id', '') is null
        and created_by_client_id is null
      )
      or (
        created_by_client_id = ((select auth.jwt()) ->> 'client_id')
        and (select public.wenyan_has_oauth_capability('preferences:write'))
      )
    )
  );

drop policy if exists "learning_preference_receipts_select_own_actor" on public.learning_preference_mutation_receipts;
create policy "learning_preference_receipts_select_own_actor"
  on public.learning_preference_mutation_receipts
  for select
  to authenticated
  using (
    (select auth.uid()) = user_id
    and client_id = coalesce(nullif((select auth.jwt()) ->> 'client_id', ''), 'direct-session')
  );

drop policy if exists "learning_preference_receipts_insert_via_rpc" on public.learning_preference_mutation_receipts;
create policy "learning_preference_receipts_insert_via_rpc"
  on public.learning_preference_mutation_receipts
  for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and client_id = coalesce(nullif((select auth.jwt()) ->> 'client_id', ''), 'direct-session')
    and (select current_setting('wenyan.preference_write_rpc', true)) = '1'
    and (
      nullif((select auth.jwt()) ->> 'client_id', '') is null
      or (select public.wenyan_has_oauth_capability('preferences:write'))
    )
  );

create or replace function public.wenyan_learning_preferences_snapshot()
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  select coalesce(
    (
      select jsonb_build_object(
        'schemaVersion', 1,
        'learningStage', jsonb_build_object(
          'current', p.stage,
          'revision', p.revision,
          'provenance', p.stage_provenance
        ),
        'stageReminder', p.stage_reminder,
        'confirmedAt', p.confirmed_at,
        'updatedAt', p.updated_at
      )
      from public.learning_preferences as p
      where p.user_id = (select auth.uid())
    ),
    jsonb_build_object(
      'schemaVersion', 1,
      'learningStage', jsonb_build_object(
        'current', 'vocabulary',
        'revision', 0,
        'provenance', jsonb_build_object(
          'kind', 'product_default',
          'ref', 'exam-prep-strategy-v1',
          'since', null
        )
      ),
      'stageReminder', null,
      'confirmedAt', null,
      'updatedAt', null
    )
  );
$$;

create or replace function public.get_learning_preferences()
returns jsonb
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_client_id text := nullif(auth.jwt() ->> 'client_id', '');
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '28000';
  end if;
  if v_client_id is not null
     and not (
       public.wenyan_has_oauth_capability('plans:read')
       or public.wenyan_has_oauth_capability('coach:auto_adjust')
       or public.wenyan_has_oauth_capability('preferences:write')
     ) then
    raise exception 'preferences_read_not_granted' using errcode = '42501';
  end if;
  return public.wenyan_learning_preferences_snapshot();
end;
$$;

create or replace function public.confirm_learning_stage(
  p_request_id text,
  p_stage text,
  p_expected_revision integer,
  p_change_reason text default ''
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_oauth_client_id text := nullif(auth.jwt() ->> 'client_id', '');
  v_actor text := coalesce(v_oauth_client_id, 'direct-session');
  v_existing public.learning_preferences%rowtype;
  v_exists boolean := false;
  v_receipt public.learning_preference_mutation_receipts%rowtype;
  v_request jsonb;
  v_response jsonb;
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '28000';
  end if;
  if v_oauth_client_id is not null and not public.wenyan_has_oauth_capability('preferences:write') then
    raise exception 'preferences_write_not_granted' using errcode = '42501';
  end if;
  if p_request_id is null
     or char_length(p_request_id) not between 8 and 120
     or p_request_id !~ '^[A-Za-z0-9._:-]+$' then
    raise exception 'invalid_request_id' using errcode = '22023';
  end if;
  if p_stage not in ('vocabulary', 'mixed', 'exam_practice') then
    raise exception 'invalid_learning_stage' using errcode = '22023';
  end if;
  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'invalid_expected_revision' using errcode = '22023';
  end if;
  if char_length(coalesce(p_change_reason, '')) > 1000 then
    raise exception 'invalid_change_reason' using errcode = '22023';
  end if;

  v_request := jsonb_build_object(
    'stage', p_stage,
    'expectedRevision', p_expected_revision,
    'changeReason', p_change_reason
  );

  select * into v_receipt
  from public.learning_preference_mutation_receipts as r
  where r.user_id = v_user_id
    and r.client_id = v_actor
    and r.request_id = p_request_id;

  if found then
    if v_receipt.operation <> 'confirm_stage' or v_receipt.request_body <> v_request then
      raise exception 'request_id_conflict' using errcode = '23505';
    end if;
    return v_receipt.response;
  end if;

  select * into v_existing
  from public.learning_preferences as p
  where p.user_id = v_user_id
  for update;
  v_exists := found;

  if (not v_exists and p_expected_revision <> 0)
     or (v_exists and v_existing.revision <> p_expected_revision) then
    raise exception 'revision_conflict' using errcode = '40001';
  end if;

  perform set_config('wenyan.preference_write_rpc', '1', true);

  if not v_exists then
    insert into public.learning_preferences (
      user_id, stage, revision, stage_provenance, stage_reminder, confirmed_at, updated_by_client_id
    ) values (
      v_user_id,
      p_stage,
      1,
      jsonb_build_object('kind', 'user_confirmation', 'ref', p_request_id, 'since', now()),
      null,
      now(),
      v_oauth_client_id
    );
  else
    update public.learning_preferences
    set stage = p_stage,
        revision = revision + 1,
        stage_provenance = jsonb_build_object('kind', 'user_confirmation', 'ref', p_request_id, 'since', now()),
        stage_reminder = null,
        confirmed_at = now(),
        updated_by_client_id = v_oauth_client_id,
        updated_at = now()
    where user_id = v_user_id;
  end if;

  v_response := public.wenyan_learning_preferences_snapshot();

  insert into public.learning_preference_revisions (
    user_id, revision, snapshot, change_reason, created_by_client_id
  ) values (
    v_user_id,
    (v_response -> 'learningStage' ->> 'revision')::integer,
    v_response,
    p_change_reason,
    v_oauth_client_id
  );

  insert into public.learning_preference_mutation_receipts (
    user_id, client_id, request_id, operation, request_body, response
  ) values (
    v_user_id, v_actor, p_request_id, 'confirm_stage', v_request, v_response
  );

  return v_response;
end;
$$;

create or replace function public.set_stage_reminder_preference(
  p_request_id text,
  p_target text,
  p_expected_revision integer,
  p_revisit_kind text,
  p_not_before timestamptz default null,
  p_additional_active_days integer default null,
  p_change_reason text default ''
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_oauth_client_id text := nullif(auth.jwt() ->> 'client_id', '');
  v_actor text := coalesce(v_oauth_client_id, 'direct-session');
  v_existing public.learning_preferences%rowtype;
  v_exists boolean := false;
  v_receipt public.learning_preference_mutation_receipts%rowtype;
  v_request jsonb;
  v_reminder jsonb;
  v_response jsonb;
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '28000';
  end if;
  if v_oauth_client_id is not null and not public.wenyan_has_oauth_capability('preferences:write') then
    raise exception 'preferences_write_not_granted' using errcode = '42501';
  end if;
  if p_request_id is null
     or char_length(p_request_id) not between 8 and 120
     or p_request_id !~ '^[A-Za-z0-9._:-]+$' then
    raise exception 'invalid_request_id' using errcode = '22023';
  end if;
  if p_target not in ('mixed', 'exam_practice') then
    raise exception 'invalid_stage_reminder_target' using errcode = '22023';
  end if;
  if p_expected_revision is null or p_expected_revision < 0 then
    raise exception 'invalid_expected_revision' using errcode = '22023';
  end if;
  if p_revisit_kind not in ('user_reopens', 'after') then
    raise exception 'invalid_stage_revisit_kind' using errcode = '22023';
  end if;
  if p_revisit_kind = 'user_reopens' and (p_not_before is not null or p_additional_active_days is not null) then
    raise exception 'invalid_stage_revisit_window' using errcode = '22023';
  end if;
  if p_revisit_kind = 'after' and (
    p_not_before is null
    or p_additional_active_days is null
    or p_additional_active_days not between 1 and 365
  ) then
    raise exception 'invalid_stage_revisit_window' using errcode = '22023';
  end if;
  if char_length(coalesce(p_change_reason, '')) > 1000 then
    raise exception 'invalid_change_reason' using errcode = '22023';
  end if;

  v_request := jsonb_build_object(
    'target', p_target,
    'expectedRevision', p_expected_revision,
    'revisitKind', p_revisit_kind,
    'notBefore', p_not_before,
    'additionalActiveDays', p_additional_active_days,
    'changeReason', p_change_reason
  );

  select * into v_receipt
  from public.learning_preference_mutation_receipts as r
  where r.user_id = v_user_id
    and r.client_id = v_actor
    and r.request_id = p_request_id;

  if found then
    if v_receipt.operation <> 'set_stage_reminder' or v_receipt.request_body <> v_request then
      raise exception 'request_id_conflict' using errcode = '23505';
    end if;
    return v_receipt.response;
  end if;

  select * into v_existing
  from public.learning_preferences as p
  where p.user_id = v_user_id
  for update;
  v_exists := found;

  if (not v_exists and p_expected_revision <> 0)
     or (v_exists and v_existing.revision <> p_expected_revision) then
    raise exception 'revision_conflict' using errcode = '40001';
  end if;
  if v_exists and v_existing.stage = p_target then
    raise exception 'invalid_stage_reminder_target' using errcode = '22023';
  end if;

  v_reminder := jsonb_build_object(
    'target', p_target,
    'declinedAt', now(),
    'provenanceRef', p_request_id,
    'revisit', case
      when p_revisit_kind = 'user_reopens'
        then jsonb_build_object('kind', 'user_reopens')
      else jsonb_build_object(
        'kind', 'after',
        'notBefore', p_not_before,
        'additionalActiveDays', p_additional_active_days
      )
    end
  );

  perform set_config('wenyan.preference_write_rpc', '1', true);

  if not v_exists then
    insert into public.learning_preferences (
      user_id, stage, revision, stage_provenance, stage_reminder, confirmed_at, updated_by_client_id
    ) values (
      v_user_id,
      'vocabulary',
      1,
      '{"kind":"product_default","ref":"exam-prep-strategy-v1","since":null}'::jsonb,
      v_reminder,
      null,
      v_oauth_client_id
    );
  else
    update public.learning_preferences
    set revision = revision + 1,
        stage_reminder = v_reminder,
        updated_by_client_id = v_oauth_client_id,
        updated_at = now()
    where user_id = v_user_id;
  end if;

  v_response := public.wenyan_learning_preferences_snapshot();

  insert into public.learning_preference_revisions (
    user_id, revision, snapshot, change_reason, created_by_client_id
  ) values (
    v_user_id,
    (v_response -> 'learningStage' ->> 'revision')::integer,
    v_response,
    p_change_reason,
    v_oauth_client_id
  );

  insert into public.learning_preference_mutation_receipts (
    user_id, client_id, request_id, operation, request_body, response
  ) values (
    v_user_id, v_actor, p_request_id, 'set_stage_reminder', v_request, v_response
  );

  return v_response;
end;
$$;

create or replace function public.clear_stage_reminder_preference(
  p_request_id text,
  p_expected_revision integer,
  p_change_reason text default ''
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := auth.uid();
  v_oauth_client_id text := nullif(auth.jwt() ->> 'client_id', '');
  v_actor text := coalesce(v_oauth_client_id, 'direct-session');
  v_existing public.learning_preferences%rowtype;
  v_receipt public.learning_preference_mutation_receipts%rowtype;
  v_request jsonb;
  v_response jsonb;
begin
  if v_user_id is null then
    raise exception 'authentication_required' using errcode = '28000';
  end if;
  if v_oauth_client_id is not null and not public.wenyan_has_oauth_capability('preferences:write') then
    raise exception 'preferences_write_not_granted' using errcode = '42501';
  end if;
  if p_request_id is null
     or char_length(p_request_id) not between 8 and 120
     or p_request_id !~ '^[A-Za-z0-9._:-]+$' then
    raise exception 'invalid_request_id' using errcode = '22023';
  end if;
  if p_expected_revision is null or p_expected_revision < 1 then
    raise exception 'invalid_expected_revision' using errcode = '22023';
  end if;
  if char_length(coalesce(p_change_reason, '')) > 1000 then
    raise exception 'invalid_change_reason' using errcode = '22023';
  end if;

  v_request := jsonb_build_object(
    'expectedRevision', p_expected_revision,
    'changeReason', p_change_reason
  );

  select * into v_receipt
  from public.learning_preference_mutation_receipts as r
  where r.user_id = v_user_id
    and r.client_id = v_actor
    and r.request_id = p_request_id;

  if found then
    if v_receipt.operation <> 'clear_stage_reminder' or v_receipt.request_body <> v_request then
      raise exception 'request_id_conflict' using errcode = '23505';
    end if;
    return v_receipt.response;
  end if;

  select * into v_existing
  from public.learning_preferences as p
  where p.user_id = v_user_id
  for update;

  if not found or v_existing.revision <> p_expected_revision then
    raise exception 'revision_conflict' using errcode = '40001';
  end if;

  perform set_config('wenyan.preference_write_rpc', '1', true);

  update public.learning_preferences
  set revision = revision + 1,
      stage_reminder = null,
      updated_by_client_id = v_oauth_client_id,
      updated_at = now()
  where user_id = v_user_id;

  v_response := public.wenyan_learning_preferences_snapshot();

  insert into public.learning_preference_revisions (
    user_id, revision, snapshot, change_reason, created_by_client_id
  ) values (
    v_user_id,
    (v_response -> 'learningStage' ->> 'revision')::integer,
    v_response,
    p_change_reason,
    v_oauth_client_id
  );

  insert into public.learning_preference_mutation_receipts (
    user_id, client_id, request_id, operation, request_body, response
  ) values (
    v_user_id, v_actor, p_request_id, 'clear_stage_reminder', v_request, v_response
  );

  return v_response;
end;
$$;

revoke all on function public.wenyan_learning_preferences_snapshot() from public, anon, authenticated;
revoke all on function public.get_learning_preferences() from public, anon, authenticated;
revoke all on function public.confirm_learning_stage(text, text, integer, text) from public, anon, authenticated;
revoke all on function public.set_stage_reminder_preference(text, text, integer, text, timestamptz, integer, text) from public, anon, authenticated;
revoke all on function public.clear_stage_reminder_preference(text, integer, text) from public, anon, authenticated;

grant execute on function public.wenyan_learning_preferences_snapshot() to authenticated;
grant execute on function public.get_learning_preferences() to authenticated;
grant execute on function public.confirm_learning_stage(text, text, integer, text) to authenticated;
grant execute on function public.set_stage_reminder_preference(text, text, integer, text, timestamptz, integer, text) to authenticated;
grant execute on function public.clear_stage_reminder_preference(text, integer, text) to authenticated;

commit;
