begin;

create table if not exists public.study_plans (
  id uuid primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  timezone text not null default 'Asia/Shanghai',
  status text not null default 'active',
  revision integer not null default 1,
  source text not null default 'wenyan-english',
  created_by_client_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint study_plans_title_length check (char_length(title) between 1 and 160),
  constraint study_plans_timezone_length check (char_length(timezone) between 1 and 64),
  constraint study_plans_status_valid check (status in ('active', 'archived')),
  constraint study_plans_revision_positive check (revision > 0),
  constraint study_plans_source_length check (char_length(source) between 1 and 64),
  unique (id, user_id)
);

create index if not exists study_plans_user_status_updated_idx
  on public.study_plans (user_id, status, updated_at desc);

create table if not exists public.plan_tasks (
  id uuid primary key,
  plan_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  position integer not null,
  kind text not null,
  title text not null,
  due_date date not null,
  estimated_minutes integer not null,
  reason text not null default '',
  config jsonb not null default '{}'::jsonb,
  state text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint plan_tasks_plan_owner_fk
    foreign key (plan_id, user_id)
    references public.study_plans(id, user_id)
    on delete cascade,
  constraint plan_tasks_position_nonnegative check (position >= 0),
  constraint plan_tasks_kind_valid check (
    kind in ('chapter', 'smart_review', 'word_set', 'dictation', 'weak_words', 'mixed_session')
  ),
  constraint plan_tasks_title_length check (char_length(title) between 1 and 160),
  constraint plan_tasks_estimated_minutes_valid check (estimated_minutes between 1 and 240),
  constraint plan_tasks_reason_length check (char_length(reason) <= 1000),
  constraint plan_tasks_config_object check (jsonb_typeof(config) = 'object'),
  constraint plan_tasks_state_valid check (state in ('active', 'cancelled')),
  unique (plan_id, position)
);

create index if not exists plan_tasks_user_due_idx
  on public.plan_tasks (user_id, due_date, position);

create table if not exists public.study_plan_revisions (
  id bigint generated by default as identity primary key,
  plan_id uuid not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  revision integer not null,
  snapshot jsonb not null,
  change_reason text not null default '',
  created_by_client_id text,
  created_at timestamptz not null default now(),
  constraint study_plan_revisions_plan_owner_fk
    foreign key (plan_id, user_id)
    references public.study_plans(id, user_id)
    on delete cascade,
  constraint study_plan_revisions_revision_positive check (revision > 0),
  constraint study_plan_revisions_snapshot_object check (jsonb_typeof(snapshot) = 'object'),
  constraint study_plan_revisions_reason_length check (char_length(change_reason) <= 1000),
  unique (plan_id, revision)
);

create index if not exists study_plan_revisions_user_plan_idx
  on public.study_plan_revisions (user_id, plan_id, revision desc);

create table if not exists public.oauth_client_capabilities (
  user_id uuid not null references auth.users(id) on delete cascade,
  client_id text not null,
  capability text not null,
  granted_at timestamptz not null default now(),
  primary key (user_id, client_id, capability),
  constraint oauth_client_capabilities_client_length check (char_length(client_id) between 1 and 200),
  constraint oauth_client_capabilities_valid check (
    capability in (
      'plans:read',
      'plans:write',
      'navigation:control',
      'session:control',
      'preferences:write',
      'coach:auto_adjust'
    )
  )
);

alter table public.study_plans enable row level security;
alter table public.plan_tasks enable row level security;
alter table public.study_plan_revisions enable row level security;
alter table public.oauth_client_capabilities enable row level security;

revoke all on table public.study_plans from public, anon, authenticated;
revoke all on table public.plan_tasks from public, anon, authenticated;
revoke all on table public.study_plan_revisions from public, anon, authenticated;
revoke all on table public.oauth_client_capabilities from public, anon, authenticated;

grant select, insert, update, delete on table public.study_plans to authenticated;
grant select, insert, update, delete on table public.plan_tasks to authenticated;
grant select on table public.study_plan_revisions to authenticated;
grant select, insert, delete on table public.oauth_client_capabilities to authenticated;

drop policy if exists "study_plans_select_own" on public.study_plans;
create policy "study_plans_select_own"
  on public.study_plans
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "study_plans_insert_direct_session" on public.study_plans;
create policy "study_plans_insert_direct_session"
  on public.study_plans
  for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and ((select auth.jwt()) ->> 'client_id') is null
    and created_by_client_id is null
  );

drop policy if exists "study_plans_update_direct_session" on public.study_plans;
create policy "study_plans_update_direct_session"
  on public.study_plans
  for update
  to authenticated
  using (
    (select auth.uid()) = user_id
    and ((select auth.jwt()) ->> 'client_id') is null
  )
  with check (
    (select auth.uid()) = user_id
    and ((select auth.jwt()) ->> 'client_id') is null
  );

drop policy if exists "study_plans_delete_direct_session" on public.study_plans;
create policy "study_plans_delete_direct_session"
  on public.study_plans
  for delete
  to authenticated
  using (
    (select auth.uid()) = user_id
    and ((select auth.jwt()) ->> 'client_id') is null
  );

drop policy if exists "plan_tasks_select_own" on public.plan_tasks;
create policy "plan_tasks_select_own"
  on public.plan_tasks
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "plan_tasks_insert_direct_session" on public.plan_tasks;
create policy "plan_tasks_insert_direct_session"
  on public.plan_tasks
  for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and ((select auth.jwt()) ->> 'client_id') is null
  );

drop policy if exists "plan_tasks_update_direct_session" on public.plan_tasks;
create policy "plan_tasks_update_direct_session"
  on public.plan_tasks
  for update
  to authenticated
  using (
    (select auth.uid()) = user_id
    and ((select auth.jwt()) ->> 'client_id') is null
  )
  with check (
    (select auth.uid()) = user_id
    and ((select auth.jwt()) ->> 'client_id') is null
  );

drop policy if exists "plan_tasks_delete_direct_session" on public.plan_tasks;
create policy "plan_tasks_delete_direct_session"
  on public.plan_tasks
  for delete
  to authenticated
  using (
    (select auth.uid()) = user_id
    and ((select auth.jwt()) ->> 'client_id') is null
  );

drop policy if exists "study_plan_revisions_select_own" on public.study_plan_revisions;
create policy "study_plan_revisions_select_own"
  on public.study_plan_revisions
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "oauth_client_capabilities_select_own" on public.oauth_client_capabilities;
create policy "oauth_client_capabilities_select_own"
  on public.oauth_client_capabilities
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists "oauth_client_capabilities_insert_direct_session" on public.oauth_client_capabilities;
create policy "oauth_client_capabilities_insert_direct_session"
  on public.oauth_client_capabilities
  for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and ((select auth.jwt()) ->> 'client_id') is null
  );

drop policy if exists "oauth_client_capabilities_delete_direct_session" on public.oauth_client_capabilities;
create policy "oauth_client_capabilities_delete_direct_session"
  on public.oauth_client_capabilities
  for delete
  to authenticated
  using (
    (select auth.uid()) = user_id
    and ((select auth.jwt()) ->> 'client_id') is null
  );

create or replace function public.get_plan_status(p_plan_id uuid default null)
returns jsonb
language sql
stable
security invoker
set search_path = ''
as $$
  with target as (
    select p.*
    from public.study_plans as p
    where p.user_id = (select auth.uid())
      and (
        (p_plan_id is not null and p.id = p_plan_id)
        or (p_plan_id is null and p.status = 'active')
      )
    order by p.updated_at desc
    limit 1
  ),
  task_rows as (
    select
      t.*,
      completion.id as completion_event_id,
      completion.occurred_at as completed_at
    from public.plan_tasks as t
    join target on target.id = t.plan_id and target.user_id = t.user_id
    left join lateral (
      select e.id, e.occurred_at
      from public.learning_events as e
      where e.user_id = t.user_id
        and e.event_type = 'chapter_completed'
        and e.payload ->> 'planId' = t.plan_id::text
        and e.payload ->> 'taskId' = t.id::text
      order by e.occurred_at desc, e.id desc
      limit 1
    ) as completion on true
  )
  select case
    when not exists (select 1 from target) then null
    else jsonb_build_object(
      'schemaVersion', 2,
      'plan', (
        select jsonb_build_object(
          'id', id,
          'title', title,
          'timezone', timezone,
          'status', status,
          'revision', revision,
          'source', source,
          'createdByClientId', created_by_client_id,
          'createdAt', created_at,
          'updatedAt', updated_at
        )
        from target
      ),
      'tasks', coalesce((
        select jsonb_agg(
          jsonb_build_object(
            'id', id,
            'position', position,
            'kind', kind,
            'title', title,
            'dueDate', due_date,
            'estimatedMinutes', estimated_minutes,
            'reason', reason,
            'config', config,
            'state', state,
            'completedAt', completed_at,
            'completionEventId', completion_event_id
          )
          order by position
        )
        from task_rows
      ), '[]'::jsonb),
      'completionPolicy', 'Completion is derived only from immutable matching learning events; plan rows cannot assert completed status.'
    )
  end;
$$;

revoke all on function public.get_plan_status(uuid) from public, anon, authenticated;
grant execute on function public.get_plan_status(uuid) to authenticated;

commit;
